### ISSUE TITLE
Dependabot script broke

### ISSUE THREAD

**Issue by dan-simon** [antimatter-dimensions/notations#362]
I think this relates to
```yml
name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - master

jobs:
  merge-me:
    name: Merge Dependabot PR
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
and https://github.com/ridedott/merge-me-action/issues/814 (saying "this method of using  ridedott/merge-me-action broke") and https://github.com/ridedott/merge-me-action#usage (how to use ridedott/merge-me-action now). In other words, we're using ridedott/merge-me-action, the way in which we were doing it broke, and we can probably fix it by using a different syntax.

However, I don't understand enough about JS ecosystem to know exactly which new syntax to use. We're a public repository so we probably want to use the public repository advice, which seems like we want to switch to something like:
```yml
on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Continuous Integration'
 ```
 rather than pull request, and also switch to v2. However, something seems pretty suspicious here and I'd probably want to do more research (why v2 instead of master?). Also, IDK if our workflow is called "Continuous Integration".
